# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MMFlexboxDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
 pod 'Yoga', '1.14.0'
 pod 'SDWebImage'
  # Pods for MMFlexboxDemo

  target 'MMFlexboxDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MMFlexboxDemoUITests' do
    # Pods for testing
  end

end
